[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs && touch database/database.sqlite && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
