[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan storage:link && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
